adiciona sumario ao readme e ordem do novo padrão
betrybe/sd-0x-mongodb-aggregations pull request #2
Opened 2020-12-16 15:21 UTC by nato-re

2020-12-16 15:24 UTC, nato-re commented on README.md
> +  * `git clone https://github.com/betrybe/sd-0x-mongodb-aggregations`.
```suggestion
  * `git clone https://github.com/tryber/sd-0x-mongodb-aggregations`.
```

2021-01-10 17:11 UTC, roziscoding commented
Temos o teste dessas alterações em staging? @nato-re por favor, adicione o link do PR de staging a esse aqui.

2021-01-26 22:12 UTC, renatosousafilho commented on README.md
> +Agora que você tem os campos essenciais, os da última pipeline:
```suggestion
Agora que você tem os campos essenciais, aplique mais um estágio na pipeline que atenda a seguinte demanda:
```

2021-01-26 22:14 UTC, renatosousafilho commented on README.md
> +#### Usando a pipeline anterior que retornar o dia com mais viagens, determine qual estação tem o maior número de viagens nesse dia da semana.
```suggestion
#### Usando a pipeline anterior que retorna o dia com mais viagens, determine qual estação tem o maior número de viagens nesse dia da semana.
```

2021-01-26 22:16 UTC, renatosousafilho commented on README.md
> +Agora que você tem os campos essenciais, os da última pipeline:
Aqui acho que fica mais evidente que é uma extensão do desafio anteriro

2021-01-26 22:16 UTC, renatosousafilho commented on README.md
> +#### Usando a pipeline anterior que retornar o dia com mais viagens, determine qual estação tem o maior número de viagens nesse dia da semana.
Pequeno typo.

2021-01-26 22:16 UTC, renatosousafilho requested changes
Alguns detalhes sobre o README.

2021-01-26 22:20 UTC, renatosousafilho commented
Questão: Como foi alterado os textos do requisitos não deveria ter sido alterado também no `requirements.json`?

2021-01-27 12:40 UTC, nato-re commented on README.md
> +Agora que você tem os campos essenciais, os da última pipeline:
Concordo plenamente :D

2021-01-27 12:40 UTC, nato-re commented on README.md
> +#### Usando a pipeline anterior que retornar o dia com mais viagens, determine qual estação tem o maior número de viagens nesse dia da semana.
Gratidão

2021-01-27 12:48 UTC, roziscoding approved these changes

2021-01-27 12:56 UTC, renatosousafilho approved these changes

2021-01-27 12:58 UTC, merged